# Generated by Django 4.2.6 on 2023-10-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_timeentry_hours_worked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
